### PR TITLE
new natives

### PR DESCRIPTION
**Pull request by ArsenalRX**
you know what to do

### CODE REVIEW

**Comment by ArsenalRX** [comment]
@DevRX please update

**Comment by DevRX** [comment]
yea i could have grabbed them. it will take a me a few. um i moved the DB msg me for new one @ArsenalRX im going to try and get the other 2 on pulling the old project to rework the menu and GUI for this one since we are using the old base for it but making some changes. we really got to code a new base i have started one about 3500 lines in i can send it over if you want

**Comment by ArsenalRX** [comment]
> yea i could have grabbed them. it will take a me a few. um i moved the DB msg me for new one @ArsenalRX im going to try and get the other 2 on pulling the old project to rework the menu and GUI for this one since we are using the old base for it but making some changes. we really got to code a new base i have started one about 3500 lines in i can send it over if you want

yea send it over ill look through it. and yea we need a new base 😔 the original isnt going to work much longer ill get the rest of the team on it

**Comment by DevRX** [comment]
> > yea i could have grabbed them. it will take a me a few. um i moved the DB msg me for new one @ArsenalRX im going to try and get the other 2 on pulling the old project to rework the menu and GUI for this one since we are using the old base for it but making some changes. we really got to code a new base i have started one about 3500 lines in i can send it over if you want
> 
> yea send it over ill look through it. and yea we need a new base 😔 the original isnt going to work much longer ill get the rest of the team on it

yea true. im going to sleep ill work on it tomorrow hoping to test in the next month or so maybe we should out out a invite beta??? 🤨

**Pull request merged**
